build:
  version: "1.0"

cards:
  message: "Get card's information on QA APIs"
  contactDetails:
    name: "Robert cards developer"
    email: "trangbn580@gmail,com"
  onCallSupport:
    - (777)123-123
    - (777)123-255