build:
  version: "2.0"

accounts:
  message: "Welcome to Ezmicroservice related to QA APIs"
  contactDetails:
    name: "Robert - QA Lead"
    email: "qalead@gmail.com"
  onCallSupport:
    - (666)555-1234
    - (666)555-1235