build:
  version: "3.0"

accounts:
  message: "Welcome to Ezmicroservice related to local APIs"
  contactDetails:
    name: "Robert - developer"
    email: "trangbn580@gmail.com"
  onCallSupport:
    - (555)555-1234
    - (555)555-1235